meals_on_wheels/core/urls.py
from django.urls import path
from .views import IndexView

app_name = 'core'

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
]

meals_on_wheels/meals_on_wheels/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('__debug__/', include('debug_toolbar.urls')),
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('customers/', include('customers.urls')),
    path('products/', include('products.urls')),
    path('orders/', include('orders.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

meals_on_wheels/orders/urls.py
from django.urls import path

from .views import (
                    CartView,
                    CheckoutView,
                    UpdateItemView,
                    ThankYouView,
                    DispatchPaymentView,
                    ProcessStripePayment,
                    CreateStripeSessionView,
                    SuccessStripeView,
                    CancelStripeView,
                    ProcessBonusPayment,
                    EmptyCartView,
                    )

app_name = 'orders'

urlpatterns = [
    path(
         'cart/',
         CartView.as_view(),
         name='cart'
         ),
    path(
         'update_item/',
         UpdateItemView.as_view(),
         name='update_item'
         ),
    path(
         'checkout/',
         CheckoutView.as_view(),
         name='checkout'
         ),
    path(
         'dispatch_payment/',
         DispatchPaymentView.as_view(),
         name='dispatch_payment'
         ),
    path(
         'bonus_payment/',
         ProcessBonusPayment.as_view(),
         name='bonus_payment'
         ),
    path(
         'stripe_payment/',
         ProcessStripePayment.as_view(),
         name='stripe_payment'
         ),
    path(
         'create-stripe-session/',
         CreateStripeSessionView.as_view(),
         name='create-stripe-session'
         ),
    path(
         'success/',
         SuccessStripeView.as_view(),
         name='success'
         ),
    path(
         'cancel/',
         CancelStripeView.as_view(),
         name='cancel'
         ),
    path(
         'thank_you/',
         ThankYouView.as_view(),
         name='thank_you'
         ),
    path(
         'empty-cart/',
         EmptyCartView.as_view(),
         name='empty_cart'
         ),
]

meals_on_wheels/products/urls.py
from django.urls import path
from .views import (
    ProductListView,
    ProductDetailView,
    CategoryView
    )

app_name = 'products'

urlpatterns = [
    path('menu/', ProductListView.as_view(), name='menu'),
    path('<slug:product_slug>/',
         ProductDetailView.as_view(),
         name='product'
         ),
    path('category/<slug:category_slug>/',
         CategoryView.as_view(),
         name='category',
         ),
]

meals_on_wheels/orders/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.forms import (
                          ModelForm,
                          Textarea,
                          TextInput,
                          )


class CheckoutForm(ModelForm):

    CHOICES = [
               ('Card', 'Credit Card (via Stripe) 💳'),
               ('Cash', 'Cash on Delivery 💵'),
               ('Bonuses', 'Pay with Bonuses 🔃'),
               ]
    payment_option = forms.ChoiceField(
                                       choices=CHOICES,
                                       widget=forms.RadioSelect()
                                       )

    comment = forms.CharField(
                              widget=Textarea(
                                  attrs={
                                         'rows': 5,
                                         'cols': 40,
                                         'class': 'form-control',
                                         'type': 'text',
                                         'name': 'comment',
                                         'placeholder': 'Comment...',
                                         }
                                             ),
                              required=False
                              )

    class Meta:
        model = get_user_model()
        fields = [
                  'first_name',
                  'last_name',
                  'phone',
                  'city',
                  'street_address'
                  ]

        widgets = {
            'first_name': TextInput(
                attrs={
                       'class': 'form-control',
                       'type': 'text',
                       'name': 'first_name',
                       'placeholder': 'First Name...',
                       }
                               ),
            'last_name': TextInput(
                attrs={
                       'class': 'form-control',
                       'type': 'text',
                       'name': 'last_name',
                       'placeholder': 'Last Name...',
                       }
                               ),
            'phone': TextInput(
                attrs={
                       'class': 'form-control',
                       'type': 'text',
                       'name': 'phone',
                       'placeholder': 'Phone...',
                       }
                               ),
            'city': TextInput(
                attrs={
                       'class': 'form-control',
                       'type': 'text',
                       'name': 'city',
                       'placeholder': 'City...',
                       }
                               ),
            'street_address': TextInput(
                attrs={
                       'class': 'form-control',
                       'type': 'text',
                       'name': 'street_address',
                       'placeholder': 'Street Address...',
                       }
                               ),
        }

meals_on_wheels/orders/views.py
from http.client import HTTPResponse
import json
from django.http.response import (
                                  HttpResponseRedirect,
                                  JsonResponse,
                                  )
from django.views.generic.base import View
from django.views.generic.edit import FormView
from django.views.generic.list import ListView
from django.views.generic import TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import (
                     Order,
                     ItemInCart,
                     )
from .forms import CheckoutForm
from products.models import (
                             Product,
                             Price,
                             )
from django.contrib.auth import get_user_model
from django.shortcuts import (
                              get_object_or_404,
                              redirect,
                              )
from django.urls import (
                         reverse,
                         reverse_lazy,
                         )
from decimal import Decimal
from django.conf import settings
import stripe


stripe.api_key = settings.STRIPE_SECRET_KEY


class CartView(LoginRequiredMixin, ListView):
    login_url = reverse_lazy('customers:login')
    model = ItemInCart
    context_object_name = 'items'
    template_name = 'orders/cart.html'

    def get_queryset(self):
        if self.request.user.is_authenticated:
            customer = self.request.user
            order, created = Order.objects.get_or_create(
                                                         customer=customer,
                                                         completed=False
                                                        )
            return order.items.all()
        else:
            return []


class CheckoutView(LoginRequiredMixin, ListView):
    login_url = reverse_lazy('customers:login')
    model = ItemInCart
    context_object_name = 'items'
    template_name = 'orders/checkout.html'

    def get(self, request, *args, **kwargs):
        customer = self.request.user
        order, created = Order.objects.get_or_create(
                                                     customer=customer,
                                                     completed=False,
                                                     )
        if not order.items.all():
            return HttpResponseRedirect(reverse('orders:empty_cart'))

        return super().get(self, request, *args, **kwargs)

    def get_queryset(self):
        if self.request.user.is_authenticated:
            customer = self.request.user
            order, created = Order.objects.get_or_create(
                             customer=customer, completed=False
                                                        )
            return order.items.all()
        else:
            return []

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.user.is_authenticated:
            customer = self.request.user
            order, created = Order.objects.get_or_create(
                             customer=customer, completed=False
                                                        )
        else:
            order = {'get_cart_total': 0, 'get_cart_items': 0}
        context['order'] = order

        customer = get_object_or_404(
                                get_user_model(),
                                pk=self.request.user.pk
                                )
        checkout_form = CheckoutForm(instance=customer)
        context['checkout_form'] = checkout_form
        # getcontext().prec = 2
        new_bonuses = order.get_cart_total * Decimal(0.01)
        customer.bonus_account += new_bonuses
        context['new_bonuses'] = f"{new_bonuses:.2f}"
        return context


class DispatchPaymentView(FormView):
    form_class = CheckoutForm

    def form_valid(self, form):
        if not self.request.user.is_authenticated:
            return HTTPResponse(
                'Sorry, it looks like you are not logged in :('
                )

        customer = self.request.user
        order, created = Order.objects.get_or_create(
                                                     customer=customer,
                                                     completed=False,
                                                     )
        order.comment = form.cleaned_data['comment']

        if not order.items.all():
            return HttpResponseRedirect(reverse('orders:empty_cart'))

        if form.cleaned_data['payment_option'] == 'Cash':
            order.payment_option = form.cleaned_data['payment_option']
            order.total = order.get_cart_total
            customer.bonus_account += (order.total * Decimal(0.01))
            order.completed = True
            order.save()
            customer.save()
            return HttpResponseRedirect(reverse('orders:thank_you'))

        elif form.cleaned_data['payment_option'] == 'Card':
            order.payment_option = 'Card'
            order.save()
            return HttpResponseRedirect(
                reverse('orders:create-stripe-session')
                )
        elif form.cleaned_data['payment_option'] == 'Bonuses':
            order.payment_option = 'Bonuses'
            order.save()
            return HttpResponseRedirect(reverse('orders:bonus_payment'))


class ProcessStripePayment(TemplateView):
    template_name = 'orders/stripe_payment.html'


class CreateStripeSessionView(View):
    def get(self, request, *args, **kwargs):
        # DOMAIN = 'http://127.0.0.1:8000'     # !! DEVELOPMENT
        DOMAIN = 'http://45.94.157.160:999'  # !! PRODUCTION
        customer = self.request.user
        order, created = Order.objects.get_or_create(
                                                     customer=customer,
                                                     completed=False,
                                                     )
        items = order.items.all()
        checkout_session = stripe.checkout.Session.create(
            line_items=[
                        {
                         'price': Price.objects.get(
                                                    product=item.product
                                                    ).stripe_price_id,
                         'quantity': item.quantity,
                         } for item in items
                         ],
            mode='payment',
            success_url=f"{DOMAIN}/orders/success/",
            cancel_url=f"{DOMAIN}/orders/cancel/",
        )
        return redirect(checkout_session.url)


class SuccessStripeView(View):

    def get(self, request):
        customer = request.user
        order = customer.history.get(completed=False)
        order.total = order.get_cart_total
        customer.bonus_account += (order.total * Decimal(0.01))
        customer.save()
        order.completed = True
        order.save()
        return HttpResponseRedirect(reverse('orders:thank_you'))


class CancelStripeView(TemplateView):
    template_name = 'orders/cancel.html'


class ProcessBonusPayment(TemplateView):
    template_name = 'orders/bonus_payment.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        customer = self.request.user
        bonuses = customer.bonus_account
        context['bonuses'] = bonuses

        order, created = Order.objects.get_or_create(
                            customer=customer, completed=False
                                                     )
        context['due_amount'] = order.get_cart_total
        context['sufficient'] = bonuses >= order.get_cart_total

        return context

    def post(self, request):
        customer = self.request.user
        order, created = Order.objects.get_or_create(
                        customer=customer, completed=False
                                                     )
        order.total = order.get_cart_total
        customer.bonus_account -= order.total
        order.completed = True
        order.save()
        customer.save()

        return HttpResponseRedirect(reverse('orders:thank_you'))


class UpdateItemView(View):
    def post(self, request):
        data = json.loads(request.body)
        productID = data['productID']
        action = data['action']

        customer = self.request.user
        product = Product.objects.get(id=productID)
        order, created = Order.objects.get_or_create(
                             customer=customer, completed=False
                                                        )

        item_in_cart, created = ItemInCart.objects.get_or_create(
                                                   order=order,
                                                   product=product
                                                   )

        if action == 'add':
            item_in_cart.quantity = item_in_cart.quantity + 1
        elif action == 'remove':
            item_in_cart.quantity = item_in_cart.quantity - 1

        if item_in_cart.quantity > 0:
            item_in_cart.save()
        else:
            item_in_cart.delete()

        return JsonResponse('Item was added', safe=False)


class ThankYouView(ListView):
    model = Product
    context_object_name = 'products'
    template_name = 'orders/thank_you.html'

    def get_queryset(self):
        return super().get_queryset().order_by('-views')[:5]


class EmptyCartView(TemplateView):
    template_name = 'orders/empty_cart.html'

meals_on_wheels/orders/templates/orders/bonus_payment.html
{% extends 'core/base.html' %}

{% block content %}

<div style="margin-top: 16px;">
    <a href="{{ request.META.HTTP_REFERER }}">&#8678; Back to Cart</a>
</div>

<hr>
<h2>Your current bonuses: <strong>{{ bonuses }}</strong></h2>
<h2>Your total order amount: <strong>${{ due_amount }}</strong></h2>
<hr>

{% if sufficient %}
    <h3>Woo-hoo! You have enough bonuses to pay for this order.</h3>
    <form action="" method="POST">
        {% csrf_token %}
        <button type="submit" class="btn btn-outline-success" style="margin-top: 20px;">Pay with Bonuses</button>
    </form>
{% else %}
    <h3>Sorry, it looks like you don't have enough bonuses to pay for this order.</h3>
    <h3>You can still pay with a credit card or good ol' cash :)</h3>
<div style="margin-top: 16px;">
    <a href="{{ request.META.HTTP_REFERER }}">&#8678; Choose a different payment method</a>
</div>
{% endif %}

{% endblock content %}

meals_on_wheels/orders/templates/orders/cancel.html
{% extends 'core/base.html' %}

{% block content %}

<div style="margin-top: 26px; text-align: center; font-family: Georgia, 'Times New Roman', Times, serif;">
    <h3 style="margin-bottom: 22px;">Forgot to add something?</h3>
    <a href="{% url 'products:menu' %}" class="btn btn-outline-dark">Go Back to Menu</a>
    <p style="margin-top: 12px;">or</p>
    <a href="{% url 'orders:cart' %}" class="btn btn-outline-dark">Go Back to Cart</a>
</div>

{% endblock content %}

meals_on_wheels/orders/templates/orders/cart.html
{% extends 'core/base.html' %}
{% load static %}
{% block content %}

<div class="row">
    <div class="col-lg-12">
        <div class="box-element">
            <a class="btn btn-outline-dark" href="{% url 'products:menu' %}" style="margin-bottom: 12px" >&#8678; Back to Menu</a>
            <br>
            <table class="table">
                <tr>
                    <th><h5>Items: <strong>{{ order.get_cart_items }}</strong></h5></th>
                    <th><h5>Total: <strong>${{ order.get_cart_total|floatformat:2 }}</strong></h5></th>
                    <th>
                        <a style="float:right; margin:5px" class="btn btn-outline-success" href="{% url 'orders:checkout' %}">Checkout</a>
                    </th>
                </tr>
            </table>
        
        </div>

        <br>

        <div class="box-element">
            <div class="cart-row" style="font-weight: 600;">
                <div style="flex:2"></div>
                <div style="flex:2">Item</div>
                <div style="flex:1">Price</div>
                <div style="flex:1">Quantity</div>
                <div style="flex:1">Subtotal</div>
            </div>
            {% for item in items %}
            <div class="cart-row">
                <div style="flex:2">
                    <a href="{{ item.product.get_absolute_url }}">
                    <img class="row-image" src="{{ item.product.imageURL }}" alt="{{ item.product.name }}"></a>
                </div>
                <div style="flex:2"><a href="{{ item.product.get_absolute_url }}">{{ item.product.name }}</a></div>
                <div style="flex:1">${{ item.product.price.all.0.get_display_price|floatformat:2 }}</div>
                <div style="flex:1">
                    <span class="quantity">{{ item.quantity }}</span>
                    <div class="quantity">
                        <span data-product="{{ item.product.id }}" data-action="add" class="chg-quantity update-cart">&#43;</span>
                        <span data-product="{{ item.product.id }}" data-action="remove" class="chg-quantity update-cart">&#8722;</span>
                    </div>
                </div>
                <div style="flex:1">${{ item.get_subtotal }}</div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>

{% endblock content %}

meals_on_wheels/orders/templates/orders/checkout.html
{% extends 'core/base.html' %}
{% load static %}
{% block content %}

<div class="row">
    <div class="col-lg-6">
        <div class="box-element" id="form-wrapper">
            <form id="form" action="{% url 'orders:dispatch_payment' %}" method="POST">
                {% csrf_token %}
                {% if not request.user.is_authenticated %}
                <div id="user-info">
                    <div class="form-field">
                        <input required class="form-control" type="text" name="name" placeholder="Name...">
                    </div>
                    <div class="form-field">
                        <input required class="form-control" type="email" name="email" placeholder="Email...">
                    </div>
                </div>
                {% endif %}
                <p>You're a few clicks away from completing your order, <strong>{{ user }}</strong>!</p>
                <hr>
                <div id="shipping-info">
                    <p style="font-size: 22px">Delivery Information:</p>
                    <hr>
                    <div class="form-field">
                        <p style="font-style: italic; font-weight: 600;">{{ checkout_form.first_name.label }}:</p>
                        {{ checkout_form.first_name }}
                    </div>
                    <br>
                    <div class="form-field">
                        <p style="font-style: italic; font-weight: 600;">{{ checkout_form.last_name.label }}:</p>
                        {{ checkout_form.last_name }}
                    </div>
                    <br>
                    <div class="form-field">
                        <p style="font-style: italic; font-weight: 600;">{{ checkout_form.city.label }}:</p>
                        {{ checkout_form.city }}
                    </div>
                    <br>
                    <div class="form-field">
                        <p style="font-style: italic; font-weight: 600;">{{ checkout_form.street_address.label }}:</p>
                        {{ checkout_form.street_address }}
                    </div>
                    <br>
                    <div class="form-field">
                        <p style="font-style: italic; font-weight: 600;">{{ checkout_form.phone.label }}:</p>
                        {{ checkout_form.phone }}
                    </div>
                    <br>
                    <hr>
                    <div class="form-field">
                        <p style="font-size: 22px;">{{ checkout_form.payment_option.label }}:</p>
                        {{ checkout_form.payment_option }}
                    </div>
                    <hr>
                    <div class="form-field">
                        <p style="font-style: italic; font-weight: 600;">{{ checkout_form.comment.label }}:</p>
                        {{ checkout_form.comment }}
                    </div>
                </div>
                    <hr>
                    <input id="form-button" class="btn btn-success w-100" type="submit" value="Confirm">
                    <!-- <button id="form-button" class="btn btn-success w-100" type='submit'>Continue</button> -->
                    <!-- <form action="" method="POST">
                        {% csrf_token %}
                        <input type="text">
                        <button type="submit">Submit</button>
                    </form> -->
            </form>
        </div>
        <br>

    </div>
    <div class="col-lg-6">
        <div class="box-element">
            <a class="btn btn-outline-dark" href="{% url 'orders:cart' %}">&#8678; Back to Cart</a>
            <hr>
            <h3>Order Summary</h3>
            <hr>
            {% for item in items %}
            <div class="cart-row">
                <div style="flex:2"><img class="row-image" src="{{ item.product.imageURL }}"></div>
                <div style="flex:2"><p>{{ item.product.name }}</p></div>
                <div style="flex:1"><p>${{ item.product.price.all.0.get_display_price|floatformat:2 }}</p></div>
                <div style="flex:1"><p>{{ item.quantity }}</p></div>
            </div>
            {% endfor %}
            <h5>Items: {{ order.get_cart_items }}</h5>
            <h5>Total: ${{ order.get_cart_total|floatformat:2 }}</h5>
            <hr>
            <h5>If paying with card or cash, you'll get <span style="color: green; font-weight: 800;">{{ new_bonuses }}</span> bonuses!</h5>
        </div>
    </div>
</div>

{% endblock content %}

meals_on_wheels/orders/templates/orders/empty_cart.html
{% extends 'core/base.html' %}

{% block content %}

<div style="margin-bottom: 12px; margin-top: 16px; text-align: center;">
    <h2>Your cart appears to be empty... Let's fix that!</p>
    <a class="btn btn-outline-dark" href="{% url 'products:menu' %}" style="margin-bottom: 12px" >&#8678; Back to Menu</a>
</div>
<br>

{% endblock content %}

meals_on_wheels/orders/templates/orders/payment.html
{% extends 'core/base.html' %}

{% block content %}



{% endblock content %}

meals_on_wheels/orders/templates/orders/stripe_payment.html
{% extends 'core/base.html' %}

{% block content %}

<div style="margin-top: 16px;">
    <a href="{{ request.META.HTTP_REFERER }}">&#8678; Back to Cart</a>
</div>

<h1>Stripe Payment Form</h1>

{% endblock content %}

meals_on_wheels/orders/templates/orders/thank_you.html
{% extends 'core/base.html' %}
{% load thumbnail %}
{% block content %}

<div style="margin-top: 26px; text-align: center; font-family: Georgia, 'Times New Roman', Times, serif;">
    <h1>Thank You! &#x1F49B;</h1>
    <h4>We'll make sure you get your order as soon as possible.</h4>
    <h4>In the meantime, you might want to check out our top 5 finger-licking, tastebud-popping meals!</h4>
</div>
<br>
<div class='row'>
{% for product in products %}
<div class="col-lg-4">
        <p><a href="{{ product.get_absolute_url }}">
            {% thumbnail product.cover_image "350x200" crop="center" as im %}
            <img class="thumbnail" src="{{ im.url }}" alt="{{ product.name }}">
            {% endthumbnail %}
        </a>
        </p>
        <div class="box-element product">
            <p><h6><strong><a href="{{ product.get_absolute_url }}">{{ product.name }}</a></strong></h6></p>
            <p>{{ product.overview }}</p>
            <hr>
            <button data-product="{{ product.id }}" data-action="add" class="btn btn-outline-secondary add-btn update-cart">Add to Cart</button>
            <h4 style="float: right">${{ product.price.all.0.get_display_price|floatformat:2 }}</h4>
        </div>
    </div>
{% endfor %}
</div>


{% endblock content %}