meals_on_wheels/core/urls.py
from django.urls import path
from .views import IndexView

app_name = 'core'

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
]

meals_on_wheels/customers/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView
from .views import (
     LoginCustomerView,
     ProfileDetailsView,
     ProfileEditView,
     RegisterView,
     CustomPasswordChangeView,
     HistoryView,
)

app_name = 'customers'

urlpatterns = [
    path('login/',
         LoginCustomerView.as_view(),
         name='login'
         ),
    path('logout/',
         LogoutView.as_view(),
         name='logout'
         ),
    path('register/',
         RegisterView.as_view(),
         name='register'
         ),
    path('profile-details/',
         ProfileDetailsView.as_view(),
         name='profile-details'
         ),
    path('profile-edit/',
         ProfileEditView.as_view(),
         name='profile-edit'
         ),
    path('password-change/',
         CustomPasswordChangeView.as_view(),
         name='password-change'
         ),
    path('history/', HistoryView.as_view(), name='history'),
]

meals_on_wheels/meals_on_wheels/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('__debug__/', include('debug_toolbar.urls')),
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('customers/', include('customers.urls')),
    path('products/', include('products.urls')),
    path('orders/', include('orders.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

meals_on_wheels/orders/urls.py
from django.urls import path

from .views import (
                    CartView,
                    CheckoutView,
                    UpdateItemView,
                    ThankYouView,
                    DispatchPaymentView,
                    ProcessStripePayment,
                    CreateStripeSessionView,
                    SuccessStripeView,
                    CancelStripeView,
                    ProcessBonusPayment,
                    EmptyCartView,
                    )

app_name = 'orders'

urlpatterns = [
    path(
         'cart/',
         CartView.as_view(),
         name='cart'
         ),
    path(
         'update_item/',
         UpdateItemView.as_view(),
         name='update_item'
         ),
    path(
         'checkout/',
         CheckoutView.as_view(),
         name='checkout'
         ),
    path(
         'dispatch_payment/',
         DispatchPaymentView.as_view(),
         name='dispatch_payment'
         ),
    path(
         'bonus_payment/',
         ProcessBonusPayment.as_view(),
         name='bonus_payment'
         ),
    path(
         'stripe_payment/',
         ProcessStripePayment.as_view(),
         name='stripe_payment'
         ),
    path(
         'create-stripe-session/',
         CreateStripeSessionView.as_view(),
         name='create-stripe-session'
         ),
    path(
         'success/',
         SuccessStripeView.as_view(),
         name='success'
         ),
    path(
         'cancel/',
         CancelStripeView.as_view(),
         name='cancel'
         ),
    path(
         'thank_you/',
         ThankYouView.as_view(),
         name='thank_you'
         ),
    path(
         'empty-cart/',
         EmptyCartView.as_view(),
         name='empty_cart'
         ),
]

meals_on_wheels/products/urls.py
from django.urls import path
from .views import (
    ProductListView,
    ProductDetailView,
    CategoryView
    )

app_name = 'products'

urlpatterns = [
    path('menu/', ProductListView.as_view(), name='menu'),
    path('<slug:product_slug>/',
         ProductDetailView.as_view(),
         name='product'
         ),
    path('category/<slug:category_slug>/',
         CategoryView.as_view(),
         name='category',
         ),
]

meals_on_wheels/core/models.py
# from django.db import models

meals_on_wheels/core/views.py
from django.views.generic import TemplateView


class IndexView(TemplateView):
    template_name = 'core/index.html'

meals_on_wheels/core/templates/core/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>Meals on Wheels</title>
    <!-- Bootstrap CSS -->
    <!-- <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous"> -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <!-- Custom CSS -->
    <link rel="stylesheet" href="{% static 'css/base.css' %}" media="all">
    <script type="text/javascript">
        const user = '{{ request.user }}'

        function getToken(name) {
        let cookieValue = null;
        if (document.cookie && document.cookie !== '') {
            const cookies = document.cookie.split(';');
            for (let i = 0; i < cookies.length; i++) {
                const cookie = cookies[i].trim();
                // Does this cookie string begin with the name we want?
                if (cookie.substring(0, name.length + 1) === (name + '=')) {
                    cookieValue = decodeURIComponent(cookie.substring(
                        name.length + 1));
                    break;
                    }
                }
            }
            return cookieValue;
        }
        const csrftoken = getToken('csrftoken');

    </script>
</head>
<body>

    {% include 'core/navbar.html' %}
    
    <div class='container'>
        {% block content %}
        
        {% endblock content %}
    </div>
        
    <!-- JavaScript Bundle with Popper -->
    <!-- <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script> -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    
    <script type="text/javascript" src="{% static 'js/cart.js' %}"></script>
</body>
</html>

meals_on_wheels/core/templates/core/index.html
{% extends 'core/base.html' %}

{% block content %}

<div style="margin-top: 80px; background-color: cornsilk; border-radius: 0%; box-shadow: 2px 2px 2px 1px rgba(17, 12, 12, 0.774); text-align: center; font-family: Georgia, 'Times New Roman', Times, serif;">
    <h1 style="font-size: 52px; margin-bottom: 25px;">Welcome{% if request.user.is_authenticated %}, <strong>{{ user }}</strong>{% endif %}! &#x1F44B;</h1>
    <h2 style="margin-bottom: 25px;">There isn't much to see on our title page...</h2>
    <h2>For all the <span class="good_tasty">good</span> &#x1F355; and <span class="good_tasty">tasty</span> &#x1F368; stuff,</h2>
    <p style="font-size: 72px;"><a href="{% url 'products:menu' %}">&#8667;SEE OUR MENU!&#8666;</a></p>
</div>


{% endblock content %}

meals_on_wheels/core/templates/core/navbar copy.html
{% load static %}

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    
    <!-- Menu -->
    <div class="navbar-collapse collapse w-50 order-1 order-md-0 dual-collapse2">
      <ul class="navbar-nav me-auto">
        <li class="nav-item">
          <a class="nav-link {% if request.path == '/products/menu/' %}active {% endif %}" aria-current="page" href="{% url 'products:menu' %}">Our Menu</a>
        </li>
      </ul>
    </div>
    
    <!-- Logo -->
    <div class="mx-auto order-0">
      <a class="navbar-brand mx-auto" style="text-decoration: underline; font-size: 26px;" href="{% url 'core:index' %}">&#x1F36A; Meals on Wheels &#x1F36A;</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".dual-collapse2">
          <span class="navbar-toggler-icon"></span>
        </button>
      </div>
      
    <!-- User-related Buttons -->
    <div class="navbar-collapse collapse w-50 order-3 dual-collapse2">
      <ul class="navbar-nav ms-auto" style="margin-left: 450px;">
        {% if request.user.is_authenticated %}
          <li class="nav-item {% if request.path == '/customers/profile-details/' %}active {% endif %}">
              <a class="nav-link" href="{% url 'customers:profile-details' %}">View Profile</a>
          </li>
          <li class="nav-item {% if request.path == '/customers/history/' %}active {% endif %}">
              <a class="nav-link" href="{% url 'customers:history' %}">History</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'customers:logout' %}">Logout</a>
          </li>
        {% else %}
          <li class="nav-item">
            <a href="{% url 'customers:login' %}" id="login-logout" class="btn btn-primary"> Login/Register</a>
          </li>
        {% endif %}
      </ul>
    </div>

    <!-- Cart -->
    <div class="navbar-collapse collapse order-4 dual-collapse2">
      <ul class="navbar-nav ms-auto">
          <li class="nav-item">
            <a href="{% url 'orders:cart' %}">
              <img  id="cart-icon" src="{% static 'images/shopping_bag.png' %}">
            </a>
          </li>
          <li class="nav-item">
            <span id="cart-total">{{ items_in_cart }}</span>
          </li>
      </ul>
    </div>
    
  </div>
</nav>

meals_on_wheels/core/templates/core/navbar.html
{% load static %}

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    
    <!-- Menu -->
    <div class="navbar-collapse collapse w-50 order-1 order-md-0 dual-collapse2">
      <ul class="navbar-nav me-auto">
        <li class="nav-item">
          <a class="nav-link {% if request.path == '/products/menu/' %}active {% endif %}" aria-current="page" href="{% url 'products:menu' %}">Our Menu</a>
        </li>
      </ul>
    </div>
    
    <!-- Logo -->
    <div class="mx-auto order-0">
      <a class="navbar-brand mx-auto" style="text-decoration: underline; font-size: 26px; font-family: Cambria, Cochin, Georgia, Times, 'Times New Roman', serif;" href="{% url 'core:index' %}">&#x1F36A; Meals on Wheels &#x1F36A;</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".dual-collapse2">
          <span class="navbar-toggler-icon"></span>
        </button>
      </div>
      
    <!-- User-related Buttons -->
    <div class="navbar-collapse collapse w-50 order-3 dual-collapse2">
      <ul class="navbar-nav ms-auto" style="margin-left: 400px;">
        {% if request.user.is_authenticated %}
          <li class="nav-item {% if request.path == '/customers/profile-details/' %}active {% endif %}">
              <a class="nav-link" href="{% url 'customers:profile-details' %}">View Profile</a>
          </li>
          <li class="nav-item {% if request.path == '/customers/history/' %}active {% endif %}">
              <a class="nav-link" href="{% url 'customers:history' %}">History</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'customers:logout' %}">Logout</a>
          </li>
        {% else %}
          <li class="nav-item">
            <a href="{% url 'customers:login' %}" id="login-logout" class="btn btn-primary"> Login/Register</a>
          </li>
        {% endif %}
      </ul>
    </div>

    <!-- Cart -->
    <div class="navbar-collapse collapse order-4 dual-collapse2">
      <ul class="navbar-nav ms-auto">
          <li class="nav-item">
            <a href="{% url 'orders:cart' %}">
              <img  id="cart-icon" src="{% static 'images/shopping_bag.png' %}">
            </a>
          </li>
          <li class="nav-item">
            <span id="cart-total">{{ items_in_cart }}</span>
          </li>
      </ul>
    </div>
    
  </div>
</nav>