meals_on_wheels/core/urls.py
from django.urls import path
from .views import IndexView

app_name = 'core'

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
]

meals_on_wheels/customers/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView
from .views import (
     LoginCustomerView,
     ProfileDetailsView,
     ProfileEditView,
     RegisterView,
     CustomPasswordChangeView,
     HistoryView,
)

app_name = 'customers'

urlpatterns = [
    path('login/',
         LoginCustomerView.as_view(),
         name='login'
         ),
    path('logout/',
         LogoutView.as_view(),
         name='logout'
         ),
    path('register/',
         RegisterView.as_view(),
         name='register'
         ),
    path('profile-details/',
         ProfileDetailsView.as_view(),
         name='profile-details'
         ),
    path('profile-edit/',
         ProfileEditView.as_view(),
         name='profile-edit'
         ),
    path('password-change/',
         CustomPasswordChangeView.as_view(),
         name='password-change'
         ),
    path('history/', HistoryView.as_view(), name='history'),
]

meals_on_wheels/meals_on_wheels/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('__debug__/', include('debug_toolbar.urls')),
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('customers/', include('customers.urls')),
    path('products/', include('products.urls')),
    path('orders/', include('orders.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

meals_on_wheels/customers/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class Customer(AbstractUser):
    phone = models.CharField(max_length=20, blank=True)
    city = models.CharField(max_length=225, blank=True)
    street_address = models.CharField(max_length=225, blank=True)
    bonus_account = models.DecimalField(
                                        default=0,
                                        max_digits=12,
                                        decimal_places=2,
                                        )

    def __str__(self) -> str:
        return self.first_name or self.username

    @property
    def get_full_name(self) -> str:
        if self.first_name is None or self.last_name is None:
            return self.username
        else:
            return f'{self.first_name} {self.last_name}'

meals_on_wheels/customers/forms.py
from django.contrib.auth import get_user_model
from django.forms import (
                          ModelForm,
                          widgets,
                          )


class ProfileForm(ModelForm):
    class Meta:
        model = get_user_model()
        fields = (
                  'username',
                  'phone',
                  'first_name',
                  'last_name',
                  'email',
                  'city',
                  'street_address'
                  )

        widgets = {
                   'email':
                   widgets.EmailInput(attrs={
                                            'placeholder':
                                            'Type in your email address',
                                            }),
                   'first_name':
                   widgets.TextInput(attrs={
                                           'placeholder':
                                           'Type in your first name',
                                           }),
                   'last_name':
                   widgets.TextInput(attrs={
                                           'placeholder':
                                           'Type in your last name',
                                           }),
                   'phone':
                   widgets.TextInput(attrs={
                                           'placeholder':
                                           'Type in your phone number',
                                           }),
                   'city':
                   widgets.TextInput(attrs={
                                           'placeholder':
                                           'Type in your city',
                                           }),
                   'street_address':
                   widgets.TextInput(attrs={
                                           'placeholder':
                                           'Type in your street address',
                                           }),
        }

        labels = {
                'email': 'Email',
        }

meals_on_wheels/customers/views.py
from django.contrib.auth.forms import (
                                       UserCreationForm,
                                       UsernameField,
                                       )
from django.contrib.auth.views import LoginView
from django.contrib.auth import (
                                 get_user_model,
                                 login,
                                 )
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.forms import SetPasswordForm
from django.contrib import messages
from django.views.generic import DetailView
from django.views.generic.edit import FormView
from django.shortcuts import (
                              get_object_or_404,
                              redirect,
                              )
from django.urls import reverse_lazy
from .forms import ProfileForm
from django.views.generic.list import ListView
from orders.models import (
                           Order,
                           ItemInCart,
                           )


class LoginCustomerView(LoginView):
    template_name = 'customers/login_register.html'
    page = 'login'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['page'] = self.page
        return context


class RegisterView(FormView):
    template_name = 'customers/login_register.html'
    success_url = '/'

    class CustomUserCreationForm(UserCreationForm):
        class Meta:
            model = get_user_model()
            fields = ("username",)
            field_classes = {'username': UsernameField}

    form_class = CustomUserCreationForm

    def form_valid(self, form):
        form.save()
        login(self.request, get_user_model()
              .objects.get(username=self.request.POST['username']))
        return super().form_valid(form)


class ProfileDetailsView(LoginRequiredMixin, DetailView):
    login_url = reverse_lazy('customers:login')
    template_name = 'customers/profile.html'
    model = get_user_model()
    context_object_name = 'customer'
    page = 'profile_details'

    def get_object(self):
        return get_user_model().objects.get(pk=self.request.user.pk)

    def get_context_data(self, **kwargs) -> dict:
        context = super().get_context_data(**kwargs)
        context['page'] = self.page
        return context


class ProfileEditView(LoginRequiredMixin, FormView):
    login_url = reverse_lazy('customers:login')
    template_name = 'customers/profile.html'
    form_class = ProfileForm
    success_url = reverse_lazy('customers:profile-details')

    def form_invalid(self, form):
        messages.error(self.request, 'Something went wrong...')
        return self.render_to_response(self.get_context_data(form=form))

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)

    def get_form_kwargs(self) -> dict:
        kwargs = super().get_form_kwargs()
        kwargs['instance'] = get_object_or_404(
                                               get_user_model(),
                                               pk=self.request.user.pk
                                               )
        return kwargs


class CustomPasswordChangeView(LoginRequiredMixin, FormView):
    login_url = reverse_lazy('customers:login')
    template_name = 'customers/password_change.html'
    form_class = SetPasswordForm

    def get_form_kwargs(self) -> dict:
        kwargs = super().get_form_kwargs()
        kwargs['user'] = get_object_or_404(get_user_model(),
                                           pk=self.request.user.id
                                           )
        return kwargs

    def form_valid(self, form):
        user = form.save()
        update_session_auth_hash(self.request, user)
        messages.success(self.request,
                         'Your password has been successfully updated!'
                         )
        return redirect(reverse_lazy('customers:profile-details'))


class HistoryView(LoginRequiredMixin, ListView):
    login_url = reverse_lazy('customers:login')
    model = Order
    context_object_name = 'history'
    template_name = 'customers/history.html'

    def get_queryset(self):
        return super().get_queryset().filter(
            customer=self.request.user,
            completed=True,
            ).order_by('-closed_on')

    def get_context_data(self, **kwargs) -> dict:
        context = super().get_context_data(**kwargs)
        items = ItemInCart.objects.all()
        orders = self.model.objects.filter(
                                           customer=self.request.user,
                                           completed=True,
                                           )
        total_orders = orders.count()
        total_items = sum(
                          order.get_cart_items
                          for order in orders
                          )
        total_spent = sum(
                          order.get_cart_total
                          for order in orders.exclude(
                            payment_option='Bonuses'
                            )
                         )
        context.update({
                        'items': items,
                        'total_orders': total_orders,
                        'total_items': total_items,
                        'total_spent': total_spent,
                        })
        return context

meals_on_wheels/customers/templates/customers/history.html
{% extends 'core/base.html' %}
{% load orders_tags %}
{% block content %}


<h3 style="text-align: center; text-decoration: underline; margin-top: 16px;">History of Your Orders:</h3>
<br>
<h4 style="font-variant: small-caps; text-decoration: underline;">Quick Summary:</h4>
<p style="font-size: 20px;">Total Number of Orders Completed: <span style="font-size: 24px; font-style: italic; font-weight: 700;">{{ total_orders }}</span></p>
<p style="font-size: 20px;">Total Number of Items Bought: <span style="font-size: 24px; font-style: italic; font-weight: 700;">{{ total_items }}</span></p>
<p style="font-size: 20px;">Total Money Spent: <span style="font-size: 24px; font-style: italic; font-weight: 700;">${{ total_spent }}</span></p>
{% for order in history %}
<table style="width: 100%; border: 1px solid black; background-color: #96D4D4; table-layout: fixed;">
    <thead>
        <tr style="font-style: italic;">
            <th>Items</th>
            <th>Total Amount</th>
            <th>Payment Option</th>
            <th>Opened</th>
            <th>Status</th>
            <th>Closed</th>
        </tr>
    </thead>
    <tbody>
        <tr style="border: 1px solid black;">
            <td>
                <ul style="margin-top: 6px;">
                    {% for item in items|items_in_order:order %}
                    <li style="padding-bottom: 10px;"><a href="{{ item.product.get_absolute_url }}">
                        <img class="row-image" src="{{ item.product.imageURL }}" alt="{{ product.name }}">
                        <br>
                        {{ item }}
                        </a>
                        <p style="font-size: 16px; font-style: italic;">&#215; {{ item.quantity }}</p>
                    </li>
                    {% endfor %}
                </ul>
            </td>
            <td>${{ order.get_cart_total }}</td>
            <td>{{ order.payment_option }}</td>
            <td>{{ order.opened_on }}</td>
            <td>{{ order.closed_on }}</td>
        </tr>
    </tbody>
</table>
<br>
{% endfor %}


{% endblock content %}

meals_on_wheels/customers/templates/customers/login_register.html
{% extends 'core/base.html' %}

{% block content %}

<div style="margin-top: 40px;">

{% if page == 'login' %}

<form action="" method="POST">
    {% csrf_token %}
    <!-- {% if form.errors %} -->
    <!-- {{ form.errors }} -->
    <!-- {% for field in form %} -->
    <!-- <ul>{{ error }}</ul> -->
    <!-- {% endfor %} -->
    <!-- {% endif %} -->
    {% if form.non_field_errors %}
        <div class="alert alert-danger">
            <strong>{{ form.non_field_errors }}</strong>
        </div>
    {% endif %}
        <div>
            <p>{{ form.username.label }}:</p>
            <p>{{ form.username }}</p>
    </div>
    <div>
        <p>{{ form.password.label }}:</p>
        <p>{{ form.password }}</p>
    </div>
    <button class="btn btn-primary" type="submit">Log in</button>
</form>
<br>
<hr>
<p>Not registered yet? &#10549;</p>
<p style="margin-left: 110px;"><span style="font-size: 22px;"></span> <a class="btn btn-warning" href="{% url 'customers:register' %}">Register</a></p>

{% else %}

<form action="" method="POST">
    {% csrf_token %}
    {% if form.non_field_errors %}
        <div class="alert alert-danger">
            <strong>{{ form.non_field_errors }}</strong>
        </div>
    {% endif %}
    {% if form.errors %}
        {% for field in form %}
            {% for error in field.errors %}
                <div class="alert alert-danger">
                    <strong>{{ error|escape }}</strong>
                </div>
            {% endfor %}
        {% endfor %}
    {% endif %}
    <div>
        <p>{{ form.username.label }}:</p>
        <p>{{ form.username }}</p>
    </div>
    <div>
        <p>{{ form.password1.label }}:</p>
        <p>{{ form.password1 }}</p>
    </div>
    <div>
        <p>{{ form.password2.label }}:</p>
        <p>{{ form.password2 }}</p>
    </div>
    <button type="submit" class="btn btn-primary">Register</button>
</form>
<br>
<hr>
<p>Already registered? &#10549;</p>
<p style="margin-left: 120px;"><span style="font-size: 22px;"></span> <a class="btn btn-warning" href="{% url 'customers:login' %}">Log in</a></p>

{% endif %}
</div>

{% endblock content %}

meals_on_wheels/customers/templates/customers/password_change.html
{% extends 'core/base.html' %}

{% block content %}

<div style="margin-top: 20px;">
    <a class="btn btn-outline-dark" href="{{ request.META.HTTP_REFERER }}" style="margin-bottom: 12px;">&#8678; Back</a>
    <hr>

    <form action="" method="POST">
        {% csrf_token %}

        {% if messages %}
        {% for message in messages %}
        {{ message }}
        {% endfor %}
        {% endif %}

        <div>
            <p>{{ form.new_password1.label }}:</p>
            <p>{{ form.new_password1 }}</p>
        </div>
        <div>
            <p>{{ form.new_password2.label }}:</p>
            <p>{{ form.new_password2 }}</p>
        </div>

        <button class="btn btn-success" type="submit">Save</button>
    </form>
    <hr>
</div>

{% endblock content %}

meals_on_wheels/customers/templates/customers/profile.html
{% extends 'core/base.html' %}

{% block content %}

<div style="margin-top: 20px;">
{% if page == 'profile_details' %}
    <hr>
    <h3><strong>Your Personal Details:</strong></h3>
    <br>
    <p><span style="font-weight: 600;">User Name</span>: <span style="margin-left: 0px;">{{ customer.username }}</span></p>
    <p><span style="font-weight: 600;">Email</span>: {% if customer.email %}{{ customer.email }}{% else %}<span style="font-style: italic;">please provide by editing your profile</span>{% endif %}</p>
    <p><span style="font-weight: 600;">First Name</span>: {% if customer.first_name %}{{ customer.first_name }}{% else %}<span style="font-style: italic;">please provide by editing your profile</span>{% endif %}</p>
    <p><span style="font-weight: 600;">Last Name</span>: {% if customer.last_name %}{{ customer.last_name }}{% else %}<span style="font-style: italic;">please provide by editing your profile</span>{% endif %}</p>
    <p><span style="font-weight: 600;">Phone</span>: {% if customer.phone %}{{ customer.phone }}{% else %}<span style="font-style: italic;">please provide by editing your profile</span>{% endif %}</p>
    <p><span style="font-weight: 600;">City</span>: {% if customer.city %}{{ customer.city }}{% else %}<span style="font-style: italic;">please provide by editing your profile</span>{% endif %}</p>
    <p><span style="font-weight: 600;">Street Address</span>: {% if customer.street_address %}{{ customer.street_address }}{% else %}<span style="font-style: italic;">please provide by editing your profile</span>{% endif %}</p>
    <a class="btn btn-danger" href="{% url 'customers:profile-edit' %}" style="margin-bottom: 22px;">Edit</a>
    <hr>
    <h3><strong>Your Bonus Account:</strong></h3>
    <p>You have <span style="color: green; font-weight: 800;">{{ customer.bonus_account }}</span> bonuses</p>
    <hr>

{% else %}
    <a class="btn btn-outline-dark" href="{% url 'customers:profile-details' %}" style="margin-bottom: 12px;">&#8678; Back</a>
    <hr>
    <form action="" method="POST">
        {% csrf_token %}
    
        <div>
            <p>{{ form.username.label }}:</p>
            <p>{{ form.username }}</p>
        </div>
        <div>
            <p>{{ form.email.label }}:</p>
            <p>{{ form.email }}</p>
        </div>
        <div>
            <p>{{ form.first_name.label }}:</p>
            <p>{{ form.first_name }}</p>
        </div>
        <div>
            <p>{{ form.last_name.label }}:</p>
            <p>{{ form.last_name }}</p>
        </div>
        <div>
            <p>{{ form.phone.label }}:</p>
            <p>{{ form.phone }}</p>
        </div>
        <div>
            <p>{{ form.city.label }}:</p>
            <p>{{ form.city }}</p>
        </div>
        <div>
            <p>{{ form.street_address.label }}:</p>
            <p>{{ form.street_address }}</p>
        </div>
        <button class="btn btn-success" type='submit'>Save</button>
    </form>
    <br>
    <hr>
    <a class="btn btn-danger" href="{% url 'customers:password-change' %}">Change Password</a>
{% endif %}
</div>

{% endblock content %}